services:
  postgres:
    image: postgres:16-alpine
    container_name: fiar-postgres
    environment:
      POSTGRES_DB: fiar
      POSTGRES_USER: fiar
      POSTGRES_PASSWORD: fiar
    ports:
      - "5432:5432"
    volumes:
      - fiar-postgres-data:/var/lib/postgresql/data

volumes:
  fiar-postgres-data:
